services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=political-scorecard
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  political-scorecard-backend:
    build:
      context: ./political-scorecard-backend
    container_name: political-scorecard-backend
    ports:
      - "8081:8080" # Map external port 8081 to internal port 8080
    volumes:
      - .:/app
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/political-scorecard
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.mariadb.jdbc.Driver
    entrypoint: ./political-scorecard-backend/startup_shell/startup_shell.sh
    depends_on:
      - mariadb
    networks:
      - app-network

  political-scorecard-frontend:
    build:
      context: ./political-scorecard-frontend
    container_name: political-scorecard-frontend
    ports:
      - "7000:7000" # Map external port 7000 to internal port 7000
    networks:
      - app-network

  keycloak:
    image: keycloak
    container_name: keycloak
    build:
      context: ./keycloak
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./proxy/Nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - political-scorecard-backend
      - political-scorecard-frontend
      - keycloak
    networks:
      - app-network

volumes:
  db-data:
  keycloak_data:
    driver: local
    driver_opts:
      type: none
      device: ./keycloak_data
      o: bind

networks:
  app-network:
    driver: bridge
