services:
  psc-mariadb:
    image: mariadb:11.5.1-ubi-rc
    container_name: psc-mariadb
    env_file: ./political-scorecard-backend/.env  # Specify the .env file to use to define environment variables
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      # We set the political-scorecard-backend to use the base SQL database to create the context and location databases and all others.
      # Therefore, no need to create a default database here.
    ports:
      - "3800:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql

  political-scorecard-backend:
    build:
      context: ./political-scorecard-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file: ./political-scorecard-backend/.env  # Specify the .env file to use to define environment variables
    environment:
      # General Spring Boot environment variables
      - SPRING_PROFILES_ACTIVE=dev
      # Database connection environment variables for primary database
      - SPRING_PRIMARY_DATASOURCE_DB_NAME
      - SPRING_PRIMARY_DATASOURCE_URL
      - SPRING_PRIMARY_DATASOURCE_USERNAME
      - SPRING_PRIMARY_DATASOURCE_PASSWORD
      - SPRING_PRIMARY_DATASOURCE_DRIVER_CLASS_NAME
      # Database connection environment variables for primary database
      - MARIADB_PSC_DATABASE_DB_NAME
      - MARIADB_PSC_DATABASE_URL
      - MARIADB_PSC_DATABASE_USERNAME
      - MARIADB_PSC_DATABASE_PASSWORD
      - MARIADB_PSC_DATABASE_DRIVER_CLASS_NAME
      # Database connection environment variables for context database
      - SPRING_CONTEXT_DATASOURCE_DB_NAME
      - SPRING_CONTEXT_DATASOURCE_URL
      - SPRING_CONTEXT_DATASOURCE_USERNAME
      - SPRING_CONTEXT_DATASOURCE_PASSWORD
      - SPRING_CONTEXT_DATASOURCE_DRIVER_CLASS_NAME
      # Database connection environment variables for location database
      - SPRING_LOCATION_DATASOURCE_DB_NAME
      - SPRING_LOCATION_DATASOURCE_URL
      - SPRING_LOCATION_DATASOURCE_USERNAME
      - SPRING_LOCATION_DATASOURCE_PASSWORD
      - SPRING_LOCATION_DATASOURCE_DRIVER_CLASS_NAME
    command: .startup_shell/backend_startup_shell.sh
    depends_on:
      - psc-mariadb
    networks:
      - psc-network

  political-scorecard-frontend:
    build:
      context: ./political-scorecard-frontend
    container_name: political-scorecard-frontend
    ports:
      - "7000:7000" # Map external port 7000 to internal port 7000
    networks:
      - psc-network

  keycloak:
    image: keycloak
    container_name: keycloak
    build:
      context: ./keycloak
    ports:
      - "2337:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
    networks:
      - psc-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./proxy/Nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - political-scorecard-backend
      - political-scorecard-frontend
      - keycloak
    networks:
      - psc-network

volumes:
  db-data:
  keycloak_data:
    driver: local
    driver_opts:
      type: none
      device: ./keycloak_data
      o: bind

networks:
  psc-network:
    driver: bridge
