services:
  psc-mariadb-test:
    image: mariadb:11.5-rc
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=political-scorecard
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  political-scorecard-backend:
    build:
      context: ./political-scorecard-backend
    container_name: political-scorecard-backend
    ports:
      - "8081:8080" # Map external port 8081 to internal port 8080
    volumes:
      - .:/app
    env_file: ./political-scorecard-backend/.env
    environment:
      # General Spring Boot environment variables
      - SPRING_PROFILES_ACTIVE=dev
      # Database connection environment variables for primary database
      - MARIADB_PSC_DATABASE_URL
      - MARIADB_PSC_DATABASE_USERNAME
      - MARIADB_PSC_DATABASE_PASSWORD
      - MARIADB_PSC_DATABASE_DRIVER_CLASS_NAME
      # Database connection environment variables for context database
      - SPRING_CONTEXT_DATASOURCE_URL
      - SPRING_CONTEXT_DATASOURCE_USERNAME
      - SPRING_CONTEXT_DATASOURCE_PASSWORD
      - SPRING_CONTEXT_DATASOURCE_DRIVER_CLASS_NAME
      # Database connection environment variables for location database
      - SPRING_LOCATION_DATASOURCE_URL
      - SPRING_LOCATION_DATASOURCE_USERNAME
      - SPRING_LOCATION_DATASOURCE_PASSWORD
      - SPRING_LOCATION_DATASOURCE_DRIVER_CLASS_NAME
    entrypoint: ./political-scorecard-backend/startup_shell/startup_shell.sh
    depends_on:
      - mariadb
    networks:
      - app-network

  political-scorecard-frontend:
    build:
      context: ./political-scorecard-frontend
    container_name: political-scorecard-frontend
    ports:
      - "7000:7000" # Map external port 7000 to internal port 7000
    networks:
      - app-network

  keycloak-test:
    image: keycloak
    container_name: keycloak
    build:
      context: ../keycloak
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data_test:/opt/keycloak/data
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
    networks:
      - app-network

  nginx-test:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./proxy/Nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - political-scorecard-backend
      - political-scorecard-frontend
      - keycloak
    networks:
      - app-network

volumes:
  db-data-test:
    driver: local
    driver_opts:
      type: none
      device: ./scorecard-test/db-data-test
      o: bind
  keycloak_data_test:
    driver: local
    driver_opts:
      type: none
      device: ./scorecard-test/keycloak_data_test
      o: bind

networks:
  app-network:
    driver: bridge