version: '3.8'

services:
  keycloak:
    image: keycloak
    networks: 
      - keycloak_network
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]

networks:
  keycloak_network:
    driver: bridge

volumes:
  keycloak_data:
    driver: local
    driver_opts:
      type: none
      device: ./keycloak_data
      o: bind